export type PartnerCategory = 'favorites' | 'everyday' | 'relationship' | 'funny' | 'future' | 'deep';

export interface PartnerQuestion {
  category: PartnerCategory;
  text: string;
  options: string[];
}

export const PARTNER_CATEGORIES: { id: PartnerCategory; label: string }[] = [
  { id: 'favorites', label: 'Favorites' },
  { id: 'everyday', label: 'Everyday' },
  { id: 'relationship', label: 'Relationship' },
  { id: 'funny', label: 'Funny' },
  { id: 'future', label: 'Future' },
  { id: 'deep', label: 'Deep' },
];

export const PARTNER_QUESTIONS: PartnerQuestion[] = [
  { category: 'favorites', text: 'What would be my ideal comfort meal?', options: ['Something homemade', 'Fast food', 'A fancy restaurant meal', 'Snacks and dessert'] },
  { category: 'favorites', text: 'Which kind of movie would I choose first?', options: ['Comedy', 'Action', 'Romance', 'Thriller or horror'] },
  { category: 'favorites', text: 'What is my preferred way to spend a free evening?', options: ['Stay home and relax', 'Go out with friends', 'Watch a movie', 'Try something new'] },
  { category: 'favorites', text: 'Which gift would make me happiest?', options: ['Something thoughtful and personal', 'Something expensive', 'An experience together', 'Something practical'] },
  { category: 'favorites', text: 'Which vacation sounds best to me?', options: ['Beach resort', 'Big-city trip', 'Nature retreat', 'Road trip'] },
  { category: 'favorites', text: 'What kind of weather do I enjoy most?', options: ['Hot and sunny', 'Cool and cloudy', 'Rainy and cozy', 'Cold and snowy'] },
  { category: 'favorites', text: 'Which type of music would I pick for a long drive?', options: ['Afrobeats or pop', 'R&B or soul', 'Hip-hop or rap', 'A mixed playlist'] },
  { category: 'favorites', text: 'Which dessert would I most likely choose?', options: ['Cake', 'Ice cream', 'Cookies', 'Fruit or something light'] },
  { category: 'favorites', text: 'What would I rather shop for?', options: ['Clothes', 'Technology', 'Home items', 'Food'] },
  { category: 'favorites', text: 'Which pet would I most enjoy having?', options: ['Dog', 'Cat', 'Bird', 'No pet'] },
  { category: 'favorites', text: 'Which social plan sounds most appealing to me?', options: ['Small dinner', 'Big party', 'Game night', 'Quiet one-on-one outing'] },
  { category: 'favorites', text: 'What kind of surprise would I enjoy most?', options: ['A planned date', 'A surprise gift', 'A visit from someone I love', 'A spontaneous trip'] },
  { category: 'everyday', text: 'What do I usually do first after waking up?', options: ['Check my phone', 'Get ready immediately', 'Stay in bed a little longer', 'Eat or drink something'] },
  { category: 'everyday', text: 'When I am stressed, what do I usually need most?', options: ['Space', 'Comfort and reassurance', 'Practical help', 'A distraction'] },
  { category: 'everyday', text: 'How do I usually make decisions?', options: ['Quickly and confidently', 'After thinking for a long time', 'By asking someone I trust', 'Based on how I feel'] },
  { category: 'everyday', text: 'Which habit of mine is most noticeable?', options: ['Being very organized', 'Running late', 'Checking my phone often', 'Overthinking'] },
  { category: 'everyday', text: 'How do I usually react when plans suddenly change?', options: ['Adapt easily', 'Get annoyed', 'Need time to adjust', 'Secretly feel relieved'] },
  { category: 'everyday', text: 'Which role do I naturally take in a group?', options: ['Leader', 'Planner', 'Entertainer', 'Quiet observer'] },
  { category: 'everyday', text: 'What is most likely to ruin my mood?', options: ['Disrespect', 'Being ignored', 'Plans going wrong', 'Feeling rushed'] },
  { category: 'everyday', text: 'What am I most likely to forget?', options: ['Where I placed something', 'An appointment', 'To reply to a message', 'Nothing — I remember everything'] },
  { category: 'everyday', text: 'How do I prefer to communicate during a disagreement?', options: ['Talk immediately', 'Take a break first', 'Text my thoughts', 'Avoid it until calm'] },
  { category: 'everyday', text: 'What kind of morning person am I?', options: ['Cheerful and energetic', 'Quiet until fully awake', 'Always rushing', 'Definitely not a morning person'] },
  { category: 'everyday', text: 'When I receive good news, who do I usually tell first?', options: ['My partner', 'A family member', 'A close friend', 'I keep it to myself for a while'] },
  { category: 'everyday', text: 'What do I value most in my daily routine?', options: ['Productivity', 'Peace and comfort', 'Freedom and flexibility', 'Time with people I care about'] },
  { category: 'relationship', text: 'What makes me feel most appreciated in the relationship?', options: ['Words of encouragement', 'Quality time', 'Helpful actions', 'Affection or gifts'] },
  { category: 'relationship', text: 'Which moment together would I most want to relive?', options: ['Our first date', 'A special trip', 'A funny unexpected moment', 'A quiet private moment'] },
  { category: 'relationship', text: 'What do I think is our biggest strength as a couple?', options: ['Communication', 'Loyalty', 'Having fun together', "Supporting each other's goals"] },
  { category: 'relationship', text: 'What kind of date would I choose for us tonight?', options: ['Dinner out', 'Movie night at home', 'An activity or game', 'A spontaneous drive'] },
  { category: 'relationship', text: 'What is the best way to apologize to me?', options: ['Say it clearly and sincerely', 'Show change through actions', 'Give me time first', 'Add a thoughtful gesture'] },
  { category: 'relationship', text: 'Which little thing from my partner matters most to me?', options: ['Checking in on me', 'Remembering small details', 'Making me laugh', 'Helping without being asked'] },
  { category: 'relationship', text: 'How do I prefer to celebrate an anniversary?', options: ['A romantic dinner', 'A trip or experience', 'A meaningful gift', 'Something simple and private'] },
  { category: 'relationship', text: 'What do I most want us to improve together?', options: ['Communication', 'Making time for each other', 'Planning the future', 'Handling disagreements'] },
  { category: 'relationship', text: 'What do I think we are most similar in?', options: ['Sense of humor', 'Values', 'Ambition', 'Lifestyle'] },
  { category: 'relationship', text: 'What do I think we are most different in?', options: ['Communication style', 'Spending habits', 'Social energy', 'Decision-making'] },
  { category: 'relationship', text: 'When I miss my partner, what do I most want?', options: ['A phone call', 'A long message', 'A surprise visit', 'Plans for the next time together'] },
  { category: 'relationship', text: 'What makes me feel safest in the relationship?', options: ['Honesty', 'Consistency', 'Affection', 'Knowing we are a team'] },
  { category: 'funny', text: 'If I became famous, what would it most likely be for?', options: ['Something impressive', 'Something funny', 'A business idea', 'An accidental viral moment'] },
  { category: 'funny', text: 'Which harmless crime would I be most likely to commit?', options: ['Stealing fries from your plate', 'Ignoring an alarm repeatedly', 'Keeping too many screenshots', 'Watching the next episode without you'] },
  { category: 'funny', text: 'If I were an animal for one day, which would I choose?', options: ['Lion', 'Dolphin', 'Eagle', 'Cat'] },
  { category: 'funny', text: 'What would I do first during a zombie apocalypse?', options: ['Find supplies', 'Call everyone I know', 'Hide somewhere safe', 'Pretend it is not happening'] },
  { category: 'funny', text: 'Which reality show would I survive best?', options: ['A cooking show', 'A dating show', 'A survival show', 'A talent competition'] },
  { category: 'funny', text: 'If I had a warning label, what would it say?', options: ['Needs food before talking', 'Can be stubborn', 'Overthinks everything', 'Laughs at the wrong time'] },
  { category: 'funny', text: 'What is my most likely late-night impulse?', options: ['Order food', 'Start a deep conversation', 'Watch random videos', 'Plan my whole future'] },
  { category: 'funny', text: 'If I could ban one minor inconvenience forever, what would it be?', options: ['Traffic', 'Slow internet', 'Long lines', 'Low phone battery'] },
  { category: 'funny', text: 'Which superpower would I misuse the most?', options: ['Reading minds', 'Teleportation', 'Invisibility', 'Stopping time'] },
  { category: 'funny', text: 'If we switched phones for a day, what would surprise you most?', options: ['My search history', 'My screenshots', 'My notes', 'How many apps are open'] },
  { category: 'funny', text: 'What would I most likely do if I won a silly trophy?', options: ['Display it proudly', 'Post it online', 'Pretend it is a major award', 'Hide it but keep it forever'] },
  { category: 'funny', text: 'Which fictional job would suit me best?', options: ['Secret agent', 'Royal advisor', 'Treasure hunter', 'Professional food tester'] },
  { category: 'future', text: 'Where would I most like us to live in the future?', options: ['A busy city', 'A quiet suburb', 'Near the beach', 'Close to family'] },
  { category: 'future', text: 'What is my biggest future priority?', options: ['Career success', 'Financial security', 'Family and relationships', 'Freedom and experiences'] },
  { category: 'future', text: 'Which shared goal would excite me most?', options: ['Traveling together', 'Building a business', 'Buying a home', 'Learning something new together'] },
  { category: 'future', text: 'How do I imagine our ideal weekend years from now?', options: ['Relaxing at home', 'Hosting friends or family', 'Going on adventures', 'Working on personal goals'] },
  { category: 'future', text: 'What kind of home would I prefer?', options: ['Modern apartment', 'Large family home', 'Cozy small house', 'Unique dream home'] },
  { category: 'future', text: 'What would I most want to save money for?', options: ['A home', 'Travel', 'A business or investment', 'A major celebration'] },
  { category: 'future', text: 'Which future milestone matters most to me?', options: ['Career achievement', 'Marriage or family milestone', 'Financial independence', 'Living in a dream location'] },
  { category: 'future', text: 'How do I feel about making long-term plans?', options: ['I love detailed plans', 'I want a broad direction', 'I prefer flexibility', 'Long-term plans make me nervous'] },
  { category: 'future', text: 'What would I most want us to be remembered for as a couple?', options: ['How much we loved each other', 'What we built together', 'How we supported others', 'How much fun we had'] },
  { category: 'future', text: 'Which lifestyle would I choose if money were no problem?', options: ['Travel often', 'Live quietly and comfortably', 'Build ambitious projects', 'Spend more time with family'] },
  { category: 'future', text: 'What skill would I most want us to learn together?', options: ['Cooking', 'A new language', 'Dancing', 'Investing or business'] },
  { category: 'future', text: 'How important is it to me that we share the same long-term goals?', options: ['Essential', 'Very important but flexible', 'Helpful, not required', 'Less important than daily happiness'] },
  { category: 'deep', text: 'What do I fear most in a serious relationship?', options: ['Losing trust', 'Growing apart', 'Not feeling understood', 'Losing independence'] },
  { category: 'deep', text: 'Which quality do I value most in a life partner?', options: ['Honesty', 'Kindness', 'Ambition', 'Emotional maturity'] },
  { category: 'deep', text: 'What is hardest for me to admit?', options: ['When I am wrong', 'When I need help', 'When I feel hurt', 'When I am afraid'] },
  { category: 'deep', text: 'What helps me feel truly understood?', options: ['Being listened to carefully', 'Receiving thoughtful advice', 'Seeing someone remember details', 'Having my feelings validated'] },
  { category: 'deep', text: 'Which personal value would I never want to compromise?', options: ['Loyalty', 'Respect', 'Freedom', 'Family'] },
  { category: 'deep', text: 'What do I think creates lasting love?', options: ['Consistent effort', 'Strong chemistry', 'Shared goals', 'Forgiveness and growth'] },
  { category: 'deep', text: 'When I feel uncertain, what kind of support do I need?', options: ['Reassurance', 'Honest perspective', 'Practical solutions', 'Quiet presence'] },
  { category: 'deep', text: 'What do I most want my partner to understand about me?', options: ['My intentions', 'My emotional needs', 'My ambitions', 'My boundaries'] },
  { category: 'deep', text: 'Which experience has shaped me most?', options: ['Family experiences', 'Education or work', 'A difficult challenge', 'An important relationship'] },
  { category: 'deep', text: 'What does success mean most to me?', options: ['Financial freedom', 'Meaningful work', 'A happy family life', 'Peace of mind'] },
  { category: 'deep', text: 'What do I find most difficult to forgive?', options: ['Dishonesty', 'Disrespect', 'Broken promises', 'Being abandoned when needed'] },
  { category: 'deep', text: 'What do I need most when I am emotionally overwhelmed?', options: ['Time alone', 'Physical comfort', 'A calm conversation', 'Help solving the problem'] },
];
