export interface ReverseClue {
  difficulty: 'easy' | 'medium' | 'hard' | 'expert';
  clue: string;
  answer: string;
  options: string[];
}

export const REVERSE_CLUES: ReverseClue[] = [
  { difficulty: 'easy', clue: 'A portable source of artificial daylight.', answer: 'Flashlight', options: ['Flashlight', 'Window', 'Mirror', 'Candle'] },
  { difficulty: 'easy', clue: 'A personal rain roof carried by one hand.', answer: 'Umbrella', options: ['Umbrella', 'Tent', 'Coat', 'Canopy'] },
  { difficulty: 'easy', clue: 'A machine that keeps food in winter all year.', answer: 'Refrigerator', options: ['Refrigerator', 'Oven', 'Cupboard', 'Freezer bag'] },
  { difficulty: 'easy', clue: 'A paper container for private words.', answer: 'Envelope', options: ['Envelope', 'Notebook', 'Folder', 'Poster'] },
  { difficulty: 'easy', clue: 'A soft platform designed for sleeping.', answer: 'Bed', options: ['Bed', 'Sofa', 'Carpet', 'Pillow'] },
  { difficulty: 'easy', clue: 'A wall opening that lets you see without leaving.', answer: 'Window', options: ['Window', 'Door', 'Mirror', 'Screen'] },
  { difficulty: 'easy', clue: 'A small machine that wakes you by making noise.', answer: 'Alarm clock', options: ['Alarm clock', 'Radio', 'Doorbell', 'Timer'] },
  { difficulty: 'easy', clue: 'A hand tool that turns a tiny metal spiral.', answer: 'Screwdriver', options: ['Screwdriver', 'Hammer', 'Wrench', 'Drill'] },
  { difficulty: 'easy', clue: 'A wearable pocket for carrying your whole day.', answer: 'Backpack', options: ['Backpack', 'Jacket', 'Wallet', 'Suitcase'] },
  { difficulty: 'easy', clue: 'A flat object that returns your face to you.', answer: 'Mirror', options: ['Mirror', 'Camera', 'Window', 'Painting'] },
  { difficulty: 'easy', clue: 'A road for trains made from two long metal lines.', answer: 'Railway track', options: ['Railway track', 'Bridge', 'Tunnel', 'Highway'] },
  { difficulty: 'easy', clue: 'A paper map of future appointments.', answer: 'Calendar', options: ['Calendar', 'Diary', 'Clock', 'Schedule'] },
  { difficulty: 'medium', clue: 'A silent instruction that points north.', answer: 'Compass', options: ['Compass', 'Map', 'Arrow', 'GPS'] },
  { difficulty: 'medium', clue: 'A bridge for electricity hidden inside plastic.', answer: 'Wire', options: ['Wire', 'Pipe', 'Cable tie', 'Fuse'] },
  { difficulty: 'medium', clue: 'A machine that turns a digital thought into paper.', answer: 'Printer', options: ['Printer', 'Scanner', 'Projector', 'Typewriter'] },
  { difficulty: 'medium', clue: 'A portable room made from fabric.', answer: 'Tent', options: ['Tent', 'Blanket', 'Cabin', 'Umbrella'] },
  { difficulty: 'medium', clue: 'A door that only allows light through.', answer: 'Curtain', options: ['Curtain', 'Window', 'Screen', 'Blind'] },
  { difficulty: 'medium', clue: 'A tiny metal promise that two pieces of fabric will stay together.', answer: 'Button', options: ['Button', 'Zipper', 'Pin', 'Buckle'] },
  { difficulty: 'medium', clue: 'A traffic controller for liquids inside a pipe.', answer: 'Valve', options: ['Valve', 'Pump', 'Funnel', 'Filter'] },
  { difficulty: 'medium', clue: "A hard shell that stores a computer's memories.", answer: 'Hard drive', options: ['Hard drive', 'Keyboard', 'Monitor', 'Router'] },
  { difficulty: 'medium', clue: 'A machine that turns moving air into electricity.', answer: 'Wind turbine', options: ['Wind turbine', 'Fan', 'Generator belt', 'Solar panel'] },
  { difficulty: 'medium', clue: 'A numbered ladder used to measure heat.', answer: 'Thermometer', options: ['Thermometer', 'Barometer', 'Scale', 'Clock'] },
  { difficulty: 'medium', clue: 'A small bridge that helps a sound enter your ear privately.', answer: 'Earbud', options: ['Earbud', 'Microphone', 'Speaker', 'Hearing aid'] },
  { difficulty: 'medium', clue: 'A mechanical hand that points at time.', answer: 'Clock hand', options: ['Clock hand', 'Compass needle', 'Dial', 'Pointer'] },
  { difficulty: 'hard', clue: 'A temporary memory that disappears when the power does.', answer: 'RAM', options: ['RAM', 'SSD', 'Cache file', 'Cloud storage'] },
  { difficulty: 'hard', clue: 'A gatekeeper that allows some network traffic and blocks the rest.', answer: 'Firewall', options: ['Firewall', 'Router', 'Password', 'Antivirus'] },
  { difficulty: 'hard', clue: 'A machine that speaks in numbers too small for the eye to see.', answer: 'Microchip', options: ['Microchip', 'Calculator', 'Barcode', 'Sensor'] },
  { difficulty: 'hard', clue: 'A picture made by listening to echoes inside the body.', answer: 'Ultrasound', options: ['Ultrasound', 'X-ray', 'MRI', 'Microscope'] },
  { difficulty: 'hard', clue: 'A scientific window that makes the very small look large.', answer: 'Microscope', options: ['Microscope', 'Telescope', 'Magnifier', 'Camera'] },
  { difficulty: 'hard', clue: 'A map of inherited instructions stored in living cells.', answer: 'DNA', options: ['DNA', 'Blood type', 'Nerve', 'Protein'] },
  { difficulty: 'hard', clue: 'A mathematical shortcut that repeats itself until a problem is solved.', answer: 'Algorithm', options: ['Algorithm', 'Equation', 'Loop', 'Formula'] },
  { difficulty: 'hard', clue: 'A light-sensitive electronic eye.', answer: 'Camera sensor', options: ['Camera sensor', 'Lens', 'Projector', 'Screen'] },
  { difficulty: 'hard', clue: 'A metal pathway that guides lightning safely into the ground.', answer: 'Lightning rod', options: ['Lightning rod', 'Antenna', 'Ground wire', 'Fence post'] },
  { difficulty: 'hard', clue: 'A sealed room where sound is reduced by absorbing its reflections.', answer: 'Anechoic chamber', options: ['Anechoic chamber', 'Studio', 'Vault', 'Vacuum chamber'] },
  { difficulty: 'hard', clue: 'A spinning store of energy that resists changes in motion.', answer: 'Flywheel', options: ['Flywheel', 'Gear', 'Pulley', 'Bearing'] },
  { difficulty: 'hard', clue: 'A one-way door for electric current.', answer: 'Diode', options: ['Diode', 'Resistor', 'Capacitor', 'Transistor'] },
  { difficulty: 'expert', clue: 'A number that can divide only by itself and one without leaving a remainder.', answer: 'Prime number', options: ['Prime number', 'Odd number', 'Natural number', 'Integer'] },
  { difficulty: 'expert', clue: 'A shape whose edge can have infinite detail while enclosing finite space.', answer: 'Fractal', options: ['Fractal', 'Spiral', 'Polygon', 'Tessellation'] },
  { difficulty: 'expert', clue: 'A machine that predicts the next symbol by studying patterns in previous symbols.', answer: 'Language model', options: ['Language model', 'Search engine', 'Compiler', 'Database'] },
  { difficulty: 'expert', clue: 'A logical statement that defeats itself when assumed true.', answer: 'Paradox', options: ['Paradox', 'Proof', 'Axiom', 'Fallacy'] },
  { difficulty: 'expert', clue: 'A storage method that remembers by trapping electric charge without moving parts.', answer: 'Flash memory', options: ['Flash memory', 'Hard disk', 'RAM', 'Magnetic tape'] },
  { difficulty: 'expert', clue: 'A communication system that sends meaning by changing a carrier wave.', answer: 'Modulation', options: ['Modulation', 'Encryption', 'Compression', 'Amplification'] },
  { difficulty: 'expert', clue: 'A network address translated from a human-readable name.', answer: 'IP address', options: ['IP address', 'Domain name', 'MAC address', 'Port'] },
  { difficulty: 'expert', clue: 'A measurement of uncertainty that also describes disorder.', answer: 'Entropy', options: ['Entropy', 'Energy', 'Variance', 'Density'] },
  { difficulty: 'expert', clue: 'A boundary beyond which information cannot return to an outside observer.', answer: 'Event horizon', options: ['Event horizon', 'Orbit', 'Singularity', 'Magnetic field'] },
  { difficulty: 'expert', clue: 'A proof method that assumes the opposite and shows it cannot be true.', answer: 'Proof by contradiction', options: ['Proof by contradiction', 'Induction', 'Deduction', 'Counterexample'] },
  { difficulty: 'expert', clue: 'A repeating vibration that travels while matter mostly stays in place.', answer: 'Wave', options: ['Wave', 'Current', 'Pulse', 'Orbit'] },
  { difficulty: 'expert', clue: 'A pattern in which small changes at the beginning can create huge differences later.', answer: 'Chaos', options: ['Chaos', 'Randomness', 'Noise', 'Feedback'] },
];
