export interface MemoryPrompt {
  category: string;
  text: string;
}

export const MEMORY_CATEGORIES = [
  { id: 'mixed', label: 'Mixed' },
  { id: 'firsts', label: 'Firsts' },
  { id: 'dates', label: 'Dates and outings' },
  { id: 'funny', label: 'Funny memories' },
  { id: 'milestones', label: 'Milestones' },
  { id: 'preferences', label: 'Shared preferences' },
];

export const MEMORY_PROMPTS: MemoryPrompt[] = [
  { category: 'firsts', text: 'Who sent the first message?' },
  { category: 'firsts', text: 'Who said “I love you” first?' },
  { category: 'firsts', text: 'Where did you first meet in person?' },
  { category: 'firsts', text: 'What was the first movie or show you watched together?' },
  { category: 'firsts', text: 'What was the first gift exchanged between you?' },
  { category: 'firsts', text: 'Who suggested the first date?' },
  { category: 'firsts', text: 'What was the first meal you shared?' },
  { category: 'firsts', text: 'What was the first song you both connected over?' },
  { category: 'firsts', text: 'Where was your first photo together taken?' },
  { category: 'firsts', text: 'What was the first nickname used in the relationship?' },
  { category: 'firsts', text: 'What was the first event you attended together?' },
  { category: 'firsts', text: 'Who introduced the other person to friends or family first?' },
  { category: 'dates', text: 'Where did you go on your first proper date?' },
  { category: 'dates', text: 'What did your partner wear on your first date?' },
  { category: 'dates', text: 'What did you eat on your first date?' },
  { category: 'dates', text: 'Who arrived first on your first date?' },
  { category: 'dates', text: 'What was the weather like on your first date?' },
  { category: 'dates', text: 'What was your most memorable date location?' },
  { category: 'dates', text: 'Which outing made you laugh the most?' },
  { category: 'dates', text: 'What was the longest trip you have taken together?' },
  { category: 'dates', text: 'Which restaurant have you visited together most often?' },
  { category: 'dates', text: 'What was the last new place you explored together?' },
  { category: 'dates', text: 'Which date required the most planning?' },
  { category: 'dates', text: 'What was your most spontaneous outing?' },
  { category: 'funny', text: 'What was your funniest misunderstanding?' },
  { category: 'funny', text: 'What is the strangest thing you have eaten together?' },
  { category: 'funny', text: 'Which inside joke do you use most?' },
  { category: 'funny', text: 'Who is more likely to get lost?' },
  { category: 'funny', text: 'What was your most embarrassing moment together?' },
  { category: 'funny', text: 'Which one of you fell asleep first during a movie?' },
  { category: 'funny', text: 'What silly disagreement do you both remember?' },
  { category: 'funny', text: 'What is the funniest nickname one of you has used?' },
  { category: 'funny', text: 'Which shared photo makes you laugh most?' },
  { category: 'funny', text: 'What is the funniest excuse either of you has made?' },
  { category: 'funny', text: 'Which one of you is more likely to forget where something was placed?' },
  { category: 'funny', text: 'What was the funniest message accidentally sent to the wrong person?' },
  { category: 'milestones', text: 'When did you officially become a couple?' },
  { category: 'milestones', text: 'What was the first major celebration you attended together?' },
  { category: 'milestones', text: 'What is the biggest challenge you have overcome together?' },
  { category: 'milestones', text: 'What was your first trip together?' },
  { category: 'milestones', text: 'What is the first important purchase you made together?' },
  { category: 'milestones', text: 'Which shared achievement are you proudest of?' },
  { category: 'milestones', text: 'What was the first difficult decision you made together?' },
  { category: 'milestones', text: 'Which birthday celebration do you remember best?' },
  { category: 'milestones', text: "When did you first meet each other's family?" },
  { category: 'milestones', text: 'What was the first future plan you seriously discussed?' },
  { category: 'milestones', text: 'Which anniversary do you remember most clearly?' },
  { category: 'milestones', text: 'What moment made the relationship feel serious?' },
  { category: 'preferences', text: 'What is your usual shared takeaway or restaurant order?' },
  { category: 'preferences', text: 'Which song best represents your relationship?' },
  { category: 'preferences', text: 'What activity do you both choose most often?' },
  { category: 'preferences', text: 'Which destination would you both most like to revisit?' },
  { category: 'preferences', text: 'What show or movie do you both quote most?' },
  { category: 'preferences', text: "What is your partner's favourite shared meal?" },
  { category: 'preferences', text: 'Which room temperature causes the most disagreement?' },
  { category: 'preferences', text: 'What time do you usually prefer to go out together?' },
  { category: 'preferences', text: 'Which type of vacation do you agree on most?' },
  { category: 'preferences', text: 'What is your favourite way to celebrate good news together?' },
  { category: 'preferences', text: 'Which shared routine would you miss most?' },
  { category: 'preferences', text: 'What small thing always improves your time together?' },
];
