import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {createMarketDay,applyMarketDay,marketDestinations,marketScores,marketScoreBreakdown,marketContractReason,marketOutcome,MARKET_BOARD,type MarketState} from '../src/lib/market-day';
import {createPocketRun,placePocketTile,pocketOffers,scorePocketBoard,replayPocketRun,validatePocketSave,POCKET_TILES,type PocketTile} from '../src/lib/pocket-paradise';
let checks=0;function check(name:string,fn:()=>void){fn();checks++;console.log('PASS '+name)}
function command(s:MarketState,c:any,id=s.players[s.turnIndex].id){return applyMarketDay(s,id,{...c,expectedVersion:s.version})}
check('Equal turns, final score and rotating leaders for 2/3/4 players',()=>{for(const n of [2,3,4]){let s=createMarketDay(Array.from({length:n},(_,i)=>'p'+i));const turns=Array(n).fill(0);while(s.phase!=='finished'){turns[s.turnIndex]++;s=command(s,{type:'move',destination:marketDestinations(s)[0]});s=command(s,{type:'pass'});s=command(s,{type:'end'});}assert.deepEqual(turns,Array(n).fill(10));assert.equal(s.version,30*n);assert.equal(marketOutcome(s).winnerIds.length,n);assert.throws(()=>command(s,{type:'end'}));}});
check('Contested contracts, affordability, immutable rejects',()=>{let s=createMarketDay(['a','b']);s.phase='business';s.players[0].position=0;s.players[1].position=3;s.stalls[0]={ownerId:'a',level:1};s.stalls[3]={ownerId:'b',level:1};const original=JSON.stringify(s);assert.throws(()=>command(s,{type:'commission',contractId:'missing'}));assert.equal(JSON.stringify(s),original);s=command(s,{type:'commission',contractId:s.contracts![0].id});assert.equal(s.contracts![0].claimedBy,'a');assert.equal(s.players[0].supplies,0);s=command(s,{type:'end'});s.phase='business';assert.match(marketContractReason(s,'b',s.contracts![0])!,/claimed/);assert.throws(()=>command(s,{type:'commission',contractId:s.contracts![0].id}));});
check('Shared stock denies last buyer and refreshes for 2/3/4 players',()=>{for(const n of [2,3,4]){let s=createMarketDay(Array.from({length:n},(_,i)=>'s'+i));for(let i=0;i<n;i++){s=command(s,{type:'move',destination:marketDestinations(s)[0]});if(i<n-1)s=command(s,{type:'supplies'});else{assert.equal(s.supplyStock,0);assert.throws(()=>command(s,{type:'supplies'}));s=command(s,{type:'pass'});}s=command(s,{type:'end'});}assert.equal(s.supplyStock,(n-1)*2);assert.equal(s.round,2);}});
check('Legacy market score and supply rules preserved',()=>{let s=createMarketDay(['a','b'],5,1);s.phase='business';s=command(s,{type:'supplies'});assert.equal(s.players[0].supplies,5);assert.equal(s.players[0].cash,9);assert.equal(s.rulesVersion,undefined);assert.equal(marketScoreBreakdown(s,'a').sets,0);});
check('Trade conservation and set recomputation',()=>{let s=createMarketDay(['a','b']);s.phase='trade';s.stalls[0]={ownerId:'a',level:1};s.stalls[3]={ownerId:'a',level:1};s.stalls[6]={ownerId:'b',level:1};const cash=s.players.reduce((a,p)=>a+p.cash,0);s=command(s,{type:'offer',toId:'b',give:{cash:5,supplies:0,stall:null},receive:{cash:0,supplies:0,stall:6}});s=command(s,{type:'accept'},'b');assert.equal(s.players.reduce((a,p)=>a+p.cash,0),cash);assert.equal(marketScoreBreakdown(s,'a').sets,7);assert.equal(s.turnIndex,1);assert.equal(s.roundTurn,1);});
check('Stale, outsider and wrong actor rejected',()=>{const s=createMarketDay(['a','b']);const before=JSON.stringify(s);assert.throws(()=>applyMarketDay(s,'a',{type:'move',destination:1,expectedVersion:99}));assert.throws(()=>command(s,{type:'move',destination:1},'c'));assert.throws(()=>command(s,{type:'move',destination:1},'b'));assert.equal(JSON.stringify(s),before);});
check('Pocket late connection activates resident; legacy save replay unchanged',()=>{const board=Array(20).fill(null);board[6]='path';board[7]='home';board[8]='park';assert.equal(scorePocketBoard(board,'x',2).happyHomes.length,0);board[5]='path';assert.equal(scorePocketBoard(board,'x',2).happyHomes.length,1);let run=createPocketRun('legacy','standard');for(let cell=0;cell<20;cell++)run=placePocketTile(run,{cell,offer:0});assert.deepEqual(validatePocketSave(run),run);assert.deepEqual(replayPocketRun(run.seed,run.mode,run.moves),run);assert.throws(()=>placePocketTile(run,{cell:0,offer:0}));});
let rndSeed=123456;const rand=()=>{rndSeed=(Math.imul(1664525,rndSeed)+1013904223)>>>0;return rndSeed/4294967296};
function pocketPolicy(seed:string,greedy:boolean){let s=createPocketRun(seed,'practice',2);for(let turn=0;turn<20;turn++){const candidates=[];for(let cell=0;cell<20;cell++)if(!s.board[cell])for(let offer=0;offer<3;offer++){const next=placePocketTile(s,{cell,offer});candidates.push({next,value:scorePocketBoard(next.board,seed,2).total+rand()*.001})}s=greedy?candidates.sort((a,b)=>b.value-a.value)[0].next:candidates[Math.floor(rand()*candidates.length)].next;}return scorePocketBoard(s.board,seed,2)}
const pocketResults:any={};for(const policy of ['random','greedy']){const results=Array.from({length:30},(_,i)=>pocketPolicy('independent-'+i,policy==='greedy'));const scores=results.map(r=>r.total).sort((a,b)=>a-b);pocketResults[policy]={wins:results.filter(r=>r.won).length,median:scores[15],min:scores[0],max:scores[29]};}
// Anneal a static target, then construct histories with a matching between offered turns and target cells.
let best:any=null;for(let restart=0;restart<12;restart++){let board=Array.from({length:20},()=>POCKET_TILES[Math.floor(rand()*4)]);board[5]='path';let fitness=(b:PocketTile[])=>{const r=scorePocketBoard(b,'target',2);return r.total+Math.min(4,r.happyHomes.length)*8+Math.min(2,r.openStalls.length)*8;};let value=fitness(board);for(let i=0;i<9000;i++){const next=[...board];const cell=Math.floor(rand()*20);if(cell===5)continue;next[cell]=POCKET_TILES[Math.floor(rand()*4)];const nv=fitness(next);const temp=3*(1-i/9000)+.08;if(nv>value||rand()<Math.exp((nv-value)/temp)){board=next;value=nv;}const r=scorePocketBoard(board,'target',2);if(r.won&&(!best||r.total>best.score.total))best={board:[...board],score:r};}}
assert.ok(best,'A winning Pocket layout exists');
const legalHistories=[];for(let i=0;i<30;i++){const seed='independent-'+i;const matched=Array(20).fill(-1);function assign(cell:number,seen:Set<number>):boolean{for(let turn=0;turn<20;turn++){if(seen.has(turn)||!pocketOffers(seed,turn,2).includes(best.board[cell]))continue;seen.add(turn);if(matched[turn]<0||assign(matched[turn],seen)){matched[turn]=cell;return true;}}return false;}assert.ok(best.board.every((_:unknown,c:number)=>assign(c,new Set())));const moves=matched.map((cell,turn)=>({cell,offer:pocketOffers(seed,turn,2).indexOf(best.board[cell])}));const run=replayPocketRun(seed,'standard',moves,2);assert.equal(scorePocketBoard(run.board,seed,2).won,true);legalHistories.push({seed,moves});}
pocketResults.planned={wins:30,score:best.score.total,medal:best.score.medal,board:best.board};
function options(s:MarketState){const id=s.players[s.turnIndex].id;const result:any[]=[];for(const destination of marketDestinations(s)){const moved=command(s,{type:'move',destination});const actions:any[]=['buy','upgrade','supplies','bank','pass'].map(type=>({type}));for(const c of moved.contracts??[])actions.push({type:'commission',contractId:c.id});for(const c of actions)try{const after=command(moved,c);result.push({destination,action:c,after});}catch{}}return result;}
function play(seed:number,policies:string[]){let s=createMarketDay(policies.map((_,i)=>'p'+i),seed);const bought:any={};while(s.phase!=='finished'){const id=s.players[s.turnIndex].id;const policy=policies[s.turnIndex];const before=marketScores(s)[id];const candidates=options(s);for(const o of candidates){const p=o.after.players[s.turnIndex];const delta=marketScores(o.after)[id]-before;const prop=o.after.stalls.filter((a:any)=>a.ownerId===id);const districts=new Set(prop.map((a:any)=>MARKET_BOARD[o.after.stalls.indexOf(a)].district));const current=s.players[s.turnIndex];o.value=delta+p.cash*.03;
if(policy==='property')o.value+=o.action.type==='buy'?7:o.action.type==='upgrade'?1:0;
if(policy==='contracts'){o.value+=o.action.type==='commission'?15:o.action.type==='buy'?(prop.length<=3?8:2):o.action.type==='supplies'&&current.supplies<3?6:0;}
if(policy==='balanced'){o.value+=o.action.type==='buy'?(11-s.round)*.5:o.action.type==='commission'?3:o.action.type==='supplies'&&current.supplies<3&&districts.size?4:0;}
}candidates.sort((a,b)=>b.value-a.value);s=command(candidates[0].after,{type:'end'});}return {scores:marketScores(s),commissions:s.players.map(p=>p.commissions),sets:s.players.map(p=>marketScoreBreakdown(s,p.id).sets)};}
const marketResults:any[]=[];for(const opponent of ['contracts','balanced'])for(const n of [2,4]){let wins=0,losses=0,ties=0,margin=0,contracts=0;for(let seed=0;seed<30;seed++)for(let seat=0;seat<n;seat++){const policies=Array(n).fill(opponent);policies[seat]='property';const r=play(seed,policies);const mine=r.scores['p'+seat];const others=Object.entries(r.scores).filter(([k])=>k!=='p'+seat).map(([,v])=>v);const max=Math.max(...others);if(mine>max)wins++;else if(mine===max)ties++;else losses++;margin+=mine-max;contracts+=r.commissions[seat];}marketResults.push({opponent,players:n,wins,losses,ties,averageMargin:margin/(30*n),propertyBotContracts:contracts});}
const offerSequences=new Set(Array.from({length:100},(_,i)=>JSON.stringify(Array.from({length:20},(_,t)=>pocketOffers('seed-'+i,t,2))))).size;
const report={checks,pocket:pocketResults,pocketDistinctOffersAcross100Seeds:offerSequences,market:marketResults};writeFileSync('qa-redesign/engine-summary.json',JSON.stringify(report,null,2)+'\n');writeFileSync('qa-redesign/pocket-winning-fixture.json',JSON.stringify({rulesVersion:2,...legalHistories[0]},null,2)+'\n');console.log(JSON.stringify(report,null,2));
