import {webkit} from 'playwright-core';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {replayPocketRun,pocketOffers} from '../src/lib/pocket-paradise.ts';
const base='http://127.0.0.1:3199';const key='gamehub:pocket-paradise:v1';const marks=[],errors=[];const mark=(name,data={})=>{marks.push({...data,name});console.log(name);};
const browser=await webkit.launch({executablePath:'/Users/blaze/Library/Caches/ms-playwright/webkit-2359/pw_run.sh',headless:true});
try{const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/play/pocket-paradise');await page.getByRole('button',{name:'Practice',exact:true}).click();
const initial=await page.evaluate(k=>localStorage.getItem(k),key);await page.locator('[data-pocket-cell="0"]').focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Cancel',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),initial);mark('Keyboard preview/cancel preserves history');
for(let cell=0;cell<20;cell++){const run=JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key));const offers=pocketOffers(run.seed,run.moves.length,2);let index=offers.findIndex(t=>t!=='path');const labels={home:'Home',park:'Park',path:'Path',stall:'Food stall'};await page.getByRole('button',{name:labels[offers[index]],exact:true}).click();await page.locator(`[data-pocket-cell="${cell}"]`).click();if(cell===5)await page.getByText('This blocks the only gate. The charter will become unreachable.').waitFor();await page.getByRole('button',{name:/^Build (home|park|path|food stall) ·/}).click();}
await page.getByRole('heading',{name:'Opening delayed'}).waitFor();mark('All twenty placements through UI; failure explains blocked gate');await page.screenshot({path:'qa-redesign/pocket-webkit-mobile-failure.png',fullPage:true});
const fixture=JSON.parse(readFileSync('qa-redesign/pocket-winning-fixture.json','utf8'));const run=replayPocketRun(fixture.seed,'practice',fixture.moves.slice(0,19),2);await page.evaluate(({key,run})=>localStorage.setItem(key,JSON.stringify(run)),{key,run});await page.reload();await page.getByText('19/20 built',{exact:true}).waitFor();const final=fixture.moves[19];const labels={home:'Home',park:'Park',path:'Path',stall:'Food stall'};await page.getByRole('button',{name:labels[pocketOffers(fixture.seed,19,2)[final.offer]],exact:true}).click();await page.locator(`[data-pocket-cell="${final.cell}"]`).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:/^Build (home|park|path|food stall) ·/}).focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'Gold charter earned'}).waitFor();mark('19-move legal fixture plus keyboard final move earns gold');const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Keep my gold postcard'}).click();const dl=await downloadEvent;await dl.saveAs('qa-redesign/pocket-webkit-gold-postcard.svg');assert.ok(readFileSync('qa-redesign/pocket-webkit-gold-postcard.svg','utf8').includes('GOLD CHARTER'));await page.reload();await page.getByRole('heading',{name:'Gold charter earned'}).waitFor();mark('Earned postcard and completed-save reload');await page.setViewportSize({width:1440,height:1000});await Promise.resolve();
await page.getByRole('button',{name:'Retry this exact challenge'}).click();await page.getByText('0/20 built',{exact:true}).waitFor();assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).seed,fixture.seed);mark('Exact challenge retry preserves seed');
const partial=replayPocketRun(fixture.seed,'practice',fixture.moves.slice(0,12),2);await page.evaluate(({key,run})=>localStorage.setItem(key,JSON.stringify(run)),{key,run:partial});await page.reload();await page.getByText('12/20 built',{exact:true}).waitFor();
const audit=[];for(const width of [320,390,820,1440])for(const theme of ['dark','light','arcade','ocean']){await page.setViewportSize({width,height:1000});await page.evaluate(t=>{document.documentElement.dataset.theme=t;localStorage.setItem('gamehub-theme',t)},theme);const geom=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(geom.scroll<=width,`${theme}/${width} overflow ${geom.scroll}`);await page.addScriptTag({content:readFileSync('node_modules/axe-core/axe.min.js','utf8')});const axe=await page.evaluate(async()=>{const r=await axe.run(document.querySelector('[class*="PocketParadise_page"]'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))}));});audit.push({width,theme,violations:axe});if(width===320&&theme==='light')await Promise.resolve();if(width===1440&&theme==='dark')await Promise.resolve();}mark('16 viewport/theme overflow checks',{axeViolationCounts:audit.map(a=>({width:a.width,theme:a.theme,count:a.violations.length}))});writeFileSync('qa-redesign/pocket-webkit-axe.json',JSON.stringify(audit,null,2));
await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='dark');const move=fixture.moves[12];await page.getByRole('button',{name:labels[pocketOffers(fixture.seed,12,2)[move.offer]],exact:true}).click();await page.locator(`[data-pocket-cell="${move.cell}"]`).click();await page.getByRole('button',{name:/^Build (home|park|path|food stall) ·/}).click();const animation=await page.locator(`[data-pocket-cell="${move.cell}"] span[class*="building"]`).evaluate(e=>getComputedStyle(e).animationName);assert.equal(animation,'none');mark('Reduced motion disables committed construction');await page.emulateMedia({reducedMotion:'no-preference'});const move2=fixture.moves[13];await page.getByRole('button',{name:labels[pocketOffers(fixture.seed,13,2)[move2.offer]],exact:true}).click();await page.locator(`[data-pocket-cell="${move2.cell}"]`).click();await page.getByRole('button',{name:/^Build (home|park|path|food stall) ·/}).click();const movement=await page.locator(`[data-pocket-cell="${move2.cell}"] span[class*="building"]`).evaluate(e=>({duration:getComputedStyle(e).animationDuration,name:getComputedStyle(e).animationName,iterations:getComputedStyle(e).animationIterationCount}));assert.notEqual(movement.name,'none');assert.equal(movement.iterations,'1');await page.waitForTimeout(600);const active=await page.evaluate(()=>document.querySelector('[class*="PocketParadise_page"]').getAnimations({subtree:true}).filter(a=>a.playState==='running').length);assert.equal(active,0);mark('Construction finite, no game animations running after settle',movement);
await page.evaluate(()=>document.body.style.zoom='2');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));mark('200% CSS zoom no page overflow');
writeFileSync('qa-redesign/pocket-webkit-browser-summary.json',JSON.stringify({marks,errors,backend:'Practice browser journeys; separate real backend suite proves API integration'},null,2));}finally{await browser.close();}
