import {chromium} from 'playwright-core';
import {createClient} from '@supabase/supabase-js';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const app='http://127.0.0.1:3199',dir='qa-workspace/evidence/';
const vars=Object.fromEntries([...readFileSync('/private/tmp/gamehub-codex-audit-20261006/local.env','utf8').matchAll(/^([A-Z_]+)="(.*)"$/gm)].map(m=>[m[1],m[2]]));assert.equal(vars.API_URL,'http://127.0.0.1:58321');
const admin=createClient(vars.API_URL,vars.SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const report={checks:[],errors:[],console:[],http:[],failed:[],layouts:[],screenshots:[],fixtures:[],cleanup:[]};
const save=()=>writeFileSync(dir+'regression-browser.json',JSON.stringify(report,null,2));
const mark=x=>{report.checks.push(x);save();console.log('PASS '+x);};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const users=[],rooms=[];
async function person(i){const name='Reg'+Date.now()+i,email=name+'@example.test',password=crypto.randomUUID()+'Q1!';const r=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username:name}});assert.ifError(r.error);users.push(r.data.user.id);report.fixtures.push({user:r.data.user.id});save();const ctx=await browser.newContext({viewport:{width:390,height:844}});const page=await ctx.newPage();page.setDefaultTimeout(18000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(['warning','error'].includes(m.type()))report.console.push({type:m.type(),text:m.text()});});page.on('response',r=>{if(r.status()>=400)report.http.push({status:r.status(),path:new URL(r.url()).pathname});});page.on('requestfailed',r=>report.failed.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText}));await page.goto(app+'/login');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL('**/games');return{page,id:r.data.user.id,name};}
async function req(p,path,data){const r=data===undefined?await p.page.request.get(app+path):await p.page.request.post(app+path,{data});const status=r.status();const body=await r.json();assert.equal(status,200,JSON.stringify(body));return body;}
async function shot(page,label){await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getTiming().iterations)).map(a=>a.finished.catch(()=>{})));});const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));report.layouts.push({label,...layout});assert(layout.scroll<=layout.width+1,label+' overflow');const path=dir+'regression-'+label+'.png';await page.screenshot({path,fullPage:true});report.screenshots.push(path);save();}
try{const a=await person(0),b=await person(1);mark('two isolated local identities login');
await a.page.getByLabel('Find a game').fill('Riddle Rush');const link=a.page.getByRole('link',{name:'Create Riddle Rush room',exact:true});await link.waitFor();await link.click();await a.page.waitForURL('**/rooms/new?game=riddle-rush');mark('library search opens existing room setup');
const game=await admin.from('games').select('id').eq('slug','riddle-rush').single();assert.ifError(game.error);const created=await req(a,'/api/rooms',{gameId:game.data.id,totalRounds:1});const code=created.code;const room=await admin.from('rooms').select('id').eq('code',code).single();assert.ifError(room.error);rooms.push(room.data.id);report.fixtures.push({room:room.data.id});save();
await a.page.goto(app+'/room/'+code);await b.page.goto(app+'/rooms/join');await b.page.getByLabel('Room code').fill(code);await b.page.getByRole('button',{name:/Join room/}).click();await b.page.waitForURL('**/room/'+code);await a.page.getByRole('button',{name:'Start with 2 players',exact:true}).click();await a.page.locator('main .option-btn').first().waitFor();await b.page.locator('main .option-btn').first().waitFor();const snapshot=await req(a,'/api/rooms/'+code);const prompt=await admin.from('prompts').select('content').eq('id',snapshot.prompt.id).single();assert.ifError(prompt.error);await shot(a.page,'quiz-playing-390');await b.page.reload();await b.page.locator('main .option-btn').first().waitFor();const after=await req(b,'/api/rooms/'+code);assert.equal(after.prompt.id,snapshot.prompt.id);mark('two-player existing quiz starts and reload preserves shared prompt');
await a.page.getByRole('button',{name:prompt.data.content.answer,exact:true}).click();await a.page.getByText(/Answer locked in/).waitFor();const locked=await a.page.locator('main .option-btn').first().isDisabled();assert(locked);await b.page.getByRole('button',{name:prompt.data.content.answer,exact:true}).click();await a.page.getByRole('button',{name:/Finish game/}).click();await a.page.getByRole('heading',{name:'Final scores',exact:true}).waitFor();await b.page.getByRole('heading',{name:'Final scores',exact:true}).waitFor();const finished=await req(a,'/api/rooms/'+code);assert.equal(finished.room.status,'finished');await shot(a.page,'quiz-results-390');const progress=await req(a,'/api/progress');assert.equal(progress.gamesPlayed,1);mark('both players answer through UI, synchronized final scores and one progress completion');
await a.page.goto(app+'/friends');await a.page.getByLabel('Search usernames').fill(b.name);await a.page.getByRole('button',{name:'Search',exact:true}).click();await a.page.getByRole('button',{name:'Follow '+b.name,exact:true}).click();await a.page.getByText('Following '+b.name+'.',{exact:true}).waitFor();const social=await req(a,'/api/social');assert.equal(social.followingCount,1);mark('social username search and follow through browser');
await a.page.goto(app+'/profile');await a.page.getByLabel('Games to play each week').fill('5');await a.page.getByRole('button',{name:'Save goal',exact:true}).click();await a.page.getByText('Weekly goal saved.',{exact:true}).waitFor();await a.page.reload();const goal=await a.page.getByLabel('Games to play each week').inputValue();assert.equal(goal,'5');mark('profile weekly goal saves and persists across reload');
for(const [theme,width] of [['dark',390],['light',768],['arcade',1440],['ocean',390]]){await a.page.evaluate(t=>{localStorage.setItem('gamehub-theme',t);},theme);await a.page.setViewportSize({width,height:900});for(const route of ['/games','/rooms','/friends','/profile','/themes']){await a.page.goto(app+route);await a.page.locator('main h1').waitFor();const actual=await a.page.locator('html').getAttribute('data-theme');assert.equal(actual,theme);await shot(a.page,route.slice(1)+'-'+theme+'-'+width);}mark(theme+' theme persistence and five routes at '+width);}
await a.page.goto(app+'/room/'+code);const leave=a.page.getByRole('button',{name:/Leave/});const count=await leave.count();if(count){a.page.once('dialog',d=>d.accept());await leave.first().click();await a.page.waitForURL('**/rooms');mark('finished existing room leaves through UI');}else{report.checks.push('No Leave control in finished room; result navigation checked separately');}
await a.page.goto(app+'/games');await a.page.getByLabel('Find a game').fill('no-such-game-regression');await a.page.getByRole('heading',{name:'No games found'}).waitFor();await a.page.getByRole('button',{name:'Show all games',exact:true}).click();await a.page.getByRole('link',{name:'Create Riddle Rush room',exact:true}).waitFor();mark('empty library search recovers to existing game');
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1;}finally{await browser.close();for(const id of rooms){const r=await admin.from('rooms').delete().eq('id',id);report.cleanup.push({room:id,error:r.error?.message??null});}for(const id of users){const r=await admin.auth.admin.deleteUser(id);report.cleanup.push({user:id,error:r.error?.message??null});}save();}
console.log(JSON.stringify({checks:report.checks.length,errors:report.errors,console:report.console,http:report.http,failed:report.failed,cleanup:report.cleanup}));
