import {chromium,webkit} from 'playwright-core';
import {createClient} from '@supabase/supabase-js';
import {readFileSync,writeFileSync,appendFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const app='http://127.0.0.1:3199';
const env=Object.fromEntries([...readFileSync('/private/tmp/gamehub-codex-audit-20261006/local.env','utf8').matchAll(/^([A-Z_]+)="(.*)"$/gm)].map(m=>[m[1],m[2]]));
assert.equal(env.API_URL,'http://127.0.0.1:58321');
const admin=createClient(env.API_URL,env.SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const report={checks:[],fixtures:[],cleaned:[],errors:[],failedRequests:[],httpErrors:[],screenshots:[],axe:[],states:[]};
const save=()=>writeFileSync(process.env.QA_SKIP_VISUAL?'qa-workspace/evidence/market-browser-final.json':'qa-workspace/evidence/market-browser.json',JSON.stringify(report,null,2));
const mark=(name,details={})=>{report.checks.push({name,...details});save();console.log('PASS',name);};
const users=[],rooms=[];let browser;
function fixture(kind,id){report.fixtures.push({kind,id});appendFileSync('qa-workspace/STATE.md',`\nCreated QA Market ${kind}: ${id}. Cleanup pending.\n`);save();}
async function person(n){const username=`QAmarket${n}${Date.now()}`,email=username+'@example.test',password=crypto.randomUUID()+'Q1!';const r=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username}});assert.ifError(r.error);users.push(r.data.user.id);fixture('user',r.data.user.id);const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const p={page,context,id:r.data.user.id,username,latest:null};page.on('pageerror',e=>report.errors.push({n,message:e.message}));page.on('requestfailed',r=>report.failedRequests.push({n,path:new URL(r.url()).pathname,error:r.failure()?.errorText}));page.on('response',async r=>{const path=new URL(r.url()).pathname;if(r.status()>=400)report.httpErrors.push({n,path,status:r.status()});if(/^\/api\/rooms\/[A-Z0-9]+$/.test(path)&&r.ok()){try{p.latest=await r.json();}catch{}}});await page.goto(app+'/login');await page.getByRole('button',{name:/show password/i}).click();await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL('**/games');return p;}
async function post(p,path,data){const r=await p.page.request.post(app+path,{data});return {status:r.status(),body:await r.json()};}
async function snapshot(p,code){const r=await p.page.request.get(app+'/api/rooms/'+code);const status=r.status();assert.equal(status,200);return r.json();}
async function register(code){const r=await admin.from('rooms').select('id').eq('code',code).single();assert.ifError(r.error);rooms.push(r.data.id);fixture('room',r.data.id);return r.data.id;}
async function action(p,label){const wait=p.page.waitForResponse(r=>r.url().endsWith('/market')&&r.request().method()==='POST');await p.page.getByRole('button',{name:label,exact:typeof label==='string'}).click();const r=await wait;const body=await r.text();assert.equal(r.status(),200,body);}
async function convergence(people,code){const authoritative=await snapshot(people[0],code);const target=authoritative.room.round_state;const deadline=Date.now()+10000;while(people.some(p=>p.latest?.room?.round_state?.version!==target.version)&&Date.now()<deadline)await new Promise(r=>setTimeout(r,100));for(const p of people){assert.equal(p.latest?.room?.round_state?.version,target.version,'peer UI refresh did not converge');assert.deepEqual(p.latest.room.round_state,target);if(authoritative.room.status==='playing'){const text=await p.page.locator('[aria-label="Market standings"]').innerText();for(const player of target.players){assert(text.includes(player.cash+' coins'));assert(text.includes(player.supplies+' supplies'));}}}report.states.push({version:target.version,phase:target.phase,round:target.round,clients:people.length});return authoritative;}
async function visual(p,tag){if(process.env.QA_SKIP_VISUAL)return;for(const theme of ['dark','light','arcade','ocean']){await p.page.evaluate(t=>{document.documentElement.dataset.theme=t;localStorage.setItem('gamehub-theme',t);window.dispatchEvent(new Event('gamehub-theme-change'));},theme);for(const width of [320,390,820,1440]){await p.page.setViewportSize({width,height:900});const dim=await p.page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,out:[...document.querySelectorAll('main button,main input,main select')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left< -1||r.right>innerWidth+1);}).map(e=>e.textContent)}));assert(dim.scroll<=dim.width+1);assert.deepEqual(dim.out,[]);const path=`qa-workspace/evidence/market-${tag}-${theme}-${width}.png`;await p.page.screenshot({path,fullPage:true});report.screenshots.push(path);}await p.page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});const violations=await p.page.evaluate(async()=>{const r=await window.axe.run({runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));});report.axe.push({tag,theme,violations});save();}mark('TC-M06 '+tag+' sixteen theme/width screenshots and full-page axe');}
try{browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const a=await person(0),b=await person(1);const people=[a,b];await a.page.getByRole('searchbox').fill('Market Day');await a.page.getByRole('link',{name:'Create Market Day room',exact:true}).click();await a.page.getByRole('button',{name:/Create room/i}).click();await a.page.waitForURL('**/room/*');const code=a.page.url().split('/').pop();const roomId=await register(code);const disabled=await a.page.getByRole('button',{name:'Waiting for a second player',exact:true}).isDisabled();assert.equal(disabled,true);const early=await post(a,`/api/rooms/${code}/start`,{});assert.equal(early.status,409);await b.page.getByRole('link',{name:/^Join(?: with code)? ↗$/}).click();await b.page.getByLabel('Room code',{exact:true}).fill(code);await b.page.getByRole('button',{name:'Join room →',exact:true}).click();await b.page.waitForURL(`**/room/${code}`);const otherStart=await post(b,`/api/rooms/${code}/start`,{});assert.equal(otherStart.status,403);await a.page.getByRole('button',{name:'Start with 2 players',exact:true}).click();await a.page.getByRole('button',{name:/Move to/}).first().waitFor();await b.page.getByRole('region',{name:'Market board'}).waitFor();await convergence(people,code);mark('TC-M01 create/join/start real controls, minimum and host denial');await a.page.getByText('How to play · scoring & tips',{exact:true}).click();const rules=await a.page.getByText('How to play · scoring & tips',{exact:true}).locator('..').innerText();assert(rules.includes('ten rounds'));assert(rules.includes('maximum 10'));await a.page.getByText('How to play · scoring & tips',{exact:true}).click();await visual(a,'movement');await a.page.setViewportSize({width:390,height:844});await a.page.getByRole('button',{name:'Flat board off',exact:true}).focus();await a.page.keyboard.press('Enter');await a.page.getByRole('button',{name:'Flat board on',exact:true}).waitFor();mark('TC-M06 keyboard flat toggle and tutorial');let turn=0;const businessSeen=new Set();
while(turn<20){let bundle=await convergence(people,code);let state=bundle.room.round_state;const actor=people.find(p=>p.id===state.players[state.turnIndex].id),other=people.find(p=>p.id!==actor.id);await actor.page.getByRole('button',{name:/Move to/}).first().waitFor();if(turn===2){await other.context.setOffline(true);mark('TC-M04 peer goes offline');}
if(turn===4){await actor.page.route('**/api/rooms/*/market',async route=>{const response=await route.fetch();const status=response.status();report.checks.push({name:'TC-M04 lost response server status',status});await route.abort('failed');},{times:1});await actor.page.getByRole('button',{name:/Move to/}).first().click();await actor.page.getByRole('alert').waitFor();await actor.page.getByRole('button',{name:/Take a break/}).waitFor();const s=await snapshot(actor,code);assert.equal(s.room.round_state.version,state.version+1);assert.equal(s.room.round_state.phase,'business');mark('TC-M04 lost successful response recovers committed state without duplicate');}else{let move=actor.page.getByRole('button',{name:/Move to/}).first();const options=await actor.page.getByRole('button',{name:/Move to/}).all();for(const opt of options){const text=await opt.innerText();if(text.includes(actor.username+' · level')&&!businessSeen.has('upgrade')){move=opt;break;}}const wait=actor.page.waitForResponse(r=>r.url().endsWith('/market')&&r.request().method()==='POST');await move.click();const response=await wait;assert.equal(response.status(),200);}
await actor.page.getByRole('button',{name:/Take a break/}).waitFor();if(turn===2){await other.context.setOffline(false);await convergence(people,code);mark('TC-M04 offline peer converges after reconnect');}else await convergence(people,code);
const choices=[['upgrade',/Upgrade your stall/],['bank',/Bank exchange/],['supplies',/Restock supplies/],['commission',/Fulfill a commission/],['buy',/Buy this stall/],['pass',/Take a break/]];let picked;for(const [type,label] of [...choices.filter(([type])=>!businessSeen.has(type)),...choices.slice().reverse()]){const enabled=await actor.page.getByRole('button',{name:label}).isEnabled();if(enabled){await action(actor,label);businessSeen.add(type);picked=type;break;}}assert(picked);await actor.page.getByRole('button',{name:'Finish turn',exact:true}).waitFor();await convergence(people,code);
if(turn<3){await actor.page.getByText('🤝 Offer a trade',{exact:true}).click();const send=actor.page.getByRole('button',{name:'Send this offer',exact:true});const emptyDisabled=await send.isDisabled();assert.equal(emptyDisabled,true);const give=actor.page.getByRole('group',{name:'You give',exact:true}),receive=actor.page.getByRole('group',{name:'You receive',exact:true});await give.getByLabel('Coins',{exact:true}).fill('1');await receive.getByLabel('Coins',{exact:true}).fill('2');if(turn===0)await visual(actor,'trade');await action(actor,'Send this offer');await other.page.getByRole('button',{name:'Accept trade',exact:true}).waitFor();await convergence(people,code);if(turn===0)await action(other,'Accept trade');else if(turn===1)await action(other,'Decline');else await action(actor,'Close offer & finish turn');mark('TC-M03 UI trade '+['accepted','declined','expired'][turn]);}else await action(actor,'Finish turn');turn++;if(turn===5){const before=await snapshot(b,code);await b.page.reload();await b.page.getByRole('region',{name:'Market board'}).waitFor();await convergence(people,code);const after=await snapshot(b,code);assert.deepEqual(after.room.round_state,before.room.round_state);mark('TC-M04 refresh resume preserves entire state');}}
await a.page.getByRole('heading',{name:'Final scores',exact:true}).waitFor();await b.page.getByRole('heading',{name:'Final scores',exact:true}).waitFor();const final=await convergence(people,code);assert.equal(final.room.status,'finished');assert.equal(final.room.round_state.round,10);const history=await admin.from('match_history').select('profile_id,score').eq('room_id',roomId);assert.ifError(history.error);assert.equal(history.data.length,2);for(const p of final.room.round_state.players){const points=p.reputation+3*p.commissions+Math.min(10,Math.floor(p.cash/3))+final.room.round_state.stalls.filter(s=>s.ownerId===p.id).reduce((v,s)=>v+2*s.level,0);assert.equal(history.data.find(h=>h.profile_id===p.id).score,points);}const retry=await post(a,`/api/rooms/${code}/market`,{type:'end',expectedVersion:final.room.round_state.version});assert.equal(retry.status,409);mark('TC-M02/05 full twenty UI turns, both results, exact score and once-only records',{businessSeen:[...businessSeen]});await visual(a,'results');await a.page.getByRole('button',{name:'🔁 Rematch (new room)',exact:true}).click();await a.page.waitForURL(u=>u.pathname.startsWith('/room/')&&!u.pathname.endsWith(code));const rematch=a.page.url().split('/').pop();await register(rematch);await b.page.goto(app+'/rooms/join');await b.page.getByLabel('Room code',{exact:true}).fill(rematch);await b.page.getByRole('button',{name:'Join room →',exact:true}).click();await a.page.getByRole('button',{name:'Start with 2 players',exact:true}).click();await a.page.getByRole('button',{name:/Move to/}).first().waitFor();const fresh=await snapshot(a,rematch);assert.equal(fresh.room.round_state.version,0);assert.equal(fresh.room.round_state.round,1);mark('TC-M05 rematch join and restart fresh');
}catch(e){report.failure={message:e.message,stack:e.stack};throw e;}finally{if(browser)await browser.close();for(const id of rooms){const r=await admin.from('rooms').delete().eq('id',id);assert.ifError(r.error);report.cleaned.push({kind:'room',id});}for(const id of users){const r=await admin.auth.admin.deleteUser(id);assert.ifError(r.error);report.cleaned.push({kind:'user',id});}appendFileSync('qa-workspace/STATE.md','\nMarket browser fixture cleanup complete; IDs and exact outcomes in evidence/market-browser.json.\n');save();}
