import {createMarketDay,applyMarketDay,marketDestinations,marketScores,MARKET_BOARD} from '../src/lib/market-day';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const checks:{name:string,result:string}[]=[];
function good(name:string,fn:()=>void){fn();checks.push({name,result:'pass'});}
function reject(name:string,s:any,id:string,command:any,pattern:RegExp){const before=structuredClone(s);let message='';try{applyMarketDay(s,id,command);}catch(e){message=(e as Error).message;}assert.match(message,pattern);assert.deepEqual(s,before);checks.push({name,result:'reject; input unchanged'});}
const base=createMarketDay(['a','b'],11);
const cmd=(type:string,extras={})=>({type,expectedVersion:0,...extras});
function state(phase='business'){const s=structuredClone(base);s.phase=phase as any;return s;}
for(const [name,ids,seed] of [['one player',['a'],1],['five players',['a','b','c','d','e'],1],['duplicate identity',['a','a'],1],['blank identity',['a',''],1],['long identity',['a','x'.repeat(129)],1],['fractional seed',['a','b'],1.5]] as const){let error;try{createMarketDay(ids as unknown as string[],seed);}catch(e){error=e;}assert(error);checks.push({name,result:'rejected'});}
good('seed deterministic three distinct options',()=>{const one=marketDestinations(base);const other=marketDestinations(createMarketDay(['a','b'],11));assert.deepEqual(one,other);assert.equal(new Set(one).size,3);});
for(const bad of [null,[],{},cmd('move',{expectedVersion:-1}),cmd('move',{expectedVersion:0.5})])reject('malformed/stale expected version',base,'a',bad,/changed/);
reject('finished command',state('finished'),'a',cmd('end'),/finished/);reject('outsider',base,'outsider',cmd('move'),/not in/);reject('wrong turn',base,'b',cmd('move'),/Wait/);
for(const input of [cmd('buy'),cmd('move',{destination:-1}),cmd('move',{destination:99}),cmd('move',{destination:1.5})])reject('movement invalid choice/type',base,'a',input,/highlighted/);
good('move allowed no fee and immutable original',()=>{const before=structuredClone(base);const dest=marketDestinations(base)[0];const next=applyMarketDay(base,'a',cmd('move',{destination:dest}));assert.equal(next.phase,'business');assert.equal(next.players[0].position,dest);assert.equal(next.version,1);assert.deepEqual(base,before);});
good('visit fee capped by empty wallet owner capped at99',()=>{const s=state('move');const dest=marketDestinations(s)[0];s.stalls[dest]={ownerId:'b',level:3};s.players[0].cash=1;s.players[1].cash=99;const n=applyMarketDay(s,'a',cmd('move',{destination:dest}));assert.equal(n.players[0].cash,0);assert.equal(n.players[1].cash,99);});
for(const owner of ['a','b']){const s=state();s.stalls[0]={ownerId:owner,level:1};reject('buy occupied '+owner,s,'a',cmd('buy'),/owner/);}
for(const type of ['buy','upgrade','supplies']){const s=state();s.players[0].cash=0;if(type==='upgrade')s.stalls[0]={ownerId:'a',level:1};reject(type+' insufficient cash',s,'a',cmd(type),/Not enough/);}
good('buy exact cost',()=>{const s=state();s.players[0].cash=4;const n=applyMarketDay(s,'a',cmd('buy'));assert.equal(n.players[0].cash,0);assert.deepEqual(n.stalls[0],{ownerId:'a',level:1});assert.equal(n.phase,'trade');});
for(const owner of [null,'b']){const s=state();s.stalls[0]={ownerId:owner,level:1};reject('upgrade non-owner '+owner,s,'a',cmd('upgrade'),/own stall/);}
{const s=state();s.stalls[0]={ownerId:'a',level:3};reject('upgrade maximum',s,'a',cmd('upgrade'),/level 3/);}
good('upgrade reaches level3 at exact cash',()=>{const s=state();s.stalls[0]={ownerId:'a',level:2};s.players[0].cash=4;const n=applyMarketDay(s,'a',cmd('upgrade'));assert.equal(n.stalls[0].level,3);assert.equal(n.players[0].cash,0);});
{const s=state();s.players[0].supplies=10;reject('supply capacity',s,'a',cmd('supplies'),/12/);}
good('supply exact12 limit',()=>{const s=state();s.players[0].supplies=9;const n=applyMarketDay(s,'a',cmd('supplies'));assert.equal(n.players[0].supplies,12);assert.equal(n.players[0].cash,9);});
reject('commission supply shortage',state(),'a',cmd('commission'),/3 supplies/);
good('commission scoring cashcap',()=>{const s=state();s.players[0].supplies=3;s.players[0].cash=98;const n=applyMarketDay(s,'a',cmd('commission'));assert.deepEqual([n.players[0].supplies,n.players[0].cash,n.players[0].commissions,n.players[0].reputation],[0,99,1,2]);});
for(const [supplies,cash] of [[1,10],[2,96]]){const s=state();Object.assign(s.players[0],{supplies,cash});reject('bank invalid capacity/supplies',s,'a',cmd('bank'),/Bank/);}
good('bank exact99 wallet',()=>{const s=state();s.players[0].cash=95;const n=applyMarketDay(s,'a',cmd('bank'));assert.deepEqual([n.players[0].cash,n.players[0].supplies],[99,0]);});
good('pass keeps assets',()=>{const s=state();const n=applyMarketDay(s,'a',cmd('pass'));assert.deepEqual(n.players,s.players);assert.equal(n.phase,'trade');});reject('business invalid action',state(),'a',cmd('end'),/business action/);
const asset={cash:1,supplies:0,stall:null};const offer=cmd('offer',{toId:'b',give:asset,receive:asset});
for(const [name,change,pattern] of [['self',{toId:'a'},/another/],['outsider',{toId:'c'},/not in/],['empty side',{give:{cash:0,supplies:0,stall:null}},/Both/],['negative',{give:{...asset,cash:-1}},/0–20/],['21 coins',{give:{...asset,cash:21}},/0–20/],['7 supplies',{give:{...asset,supplies:7}},/0–20/],['fraction',{give:{...asset,cash:0.5}},/0–20/],['badstall',{give:{...asset,stall:12}},/0–20/],['unownedstall',{give:{...asset,stall:1}},/no longer/],['unavailablecash',{give:{...asset,cash:20}},/no longer/],['unavailablesupplies',{give:{...asset,supplies:6}},/no longer/]] as const)reject('offer '+name,state('trade'),'a',{...offer,...change},pattern);
for(const [kind,value] of [['cash',99],['supplies',12]] as const){const s=state('trade');s.players[1][kind]=value;const give={cash:0,supplies:0,stall:null,[kind]:1};const receive={cash:kind==='cash'?0:1,supplies:kind==='cash'?1:0,stall:null};reject('offer '+kind+' overflow',s,'a',{...offer,give,receive},/capacity/);}
let offered=applyMarketDay(state('trade'),'a',offer);
reject('duplicate offer',offered,'a',{...offer,expectedVersion:1},/existing/);
reject('accept sender',offered,'a',{type:'accept',expectedVersion:1},/no trade/);reject('accept nooffer',state('trade'),'b',cmd('accept'),/no trade/);reject('accept wrong phase',base,'b',cmd('accept'),/no trade/);reject('trade invalid action',state('trade'),'a',cmd('buy'),/end your/);
good('accept exact two-sided transfer with ownership',()=>{const s=state('trade');s.stalls[0]={ownerId:'a',level:3};s.stalls[1]={ownerId:'b',level:2};const o=applyMarketDay(s,'a',{...offer,give:{cash:2,supplies:1,stall:0},receive:{cash:3,supplies:2,stall:1}});const n=applyMarketDay(o,'b',{type:'accept',expectedVersion:1});assert.deepEqual(n.players.map(p=>[p.cash,p.supplies]),[[13,3],[11,1]]);assert.deepEqual(n.stalls.slice(0,2),[{ownerId:'b',level:3},{ownerId:'a',level:2}]);assert.equal(n.turnIndex,1);assert.equal(n.offer,null);});
{const s=structuredClone(offered);s.players[0].cash=0;reject('accept asset unavailable recheck',s,'b',{type:'accept',expectedVersion:1},/no longer/);}
{const s=structuredClone(offered);s.offer!.receive.supplies=1;s.players[0].supplies=12;reject('accept capacity recheck',s,'b',{type:'accept',expectedVersion:1},/capacity/);}
for(const type of ['decline','end'])good(type+' drops offer no transfer',()=>{const n=applyMarketDay(offered,type==='end'?'a':'b',{type,expectedVersion:1});assert.deepEqual(n.players,offered.players);assert.equal(n.offer,null);assert.equal(n.turnIndex,1);});
for(let event=0;event<4;event++)good('round event '+event+' income caps and supply caps',()=>{const s=state('trade');s.seed=(event-7+8)%4;s.turnIndex=1;s.players[0].cash=98;s.players[0].supplies=12;for(let i=0;i<4;i++)s.stalls[i]={ownerId:'a',level:3};const n=applyMarketDay(s,'b',cmd('end'));assert.equal(n.event,event);assert.equal(n.players[0].cash,99);assert.equal(n.players[0].supplies,12);assert.equal(n.players[0].reputation,event===2?1:0);assert.equal(n.players[1].reputation,0);assert.equal(n.round,2);assert.equal(n.phase,'move');});
good('final ten round state score and log bounded',()=>{const s=state('trade');s.round=10;s.turnIndex=1;s.log=Array(50).fill('old');const n=applyMarketDay(s,'b',cmd('end'));assert.equal(n.phase,'finished');assert.equal(n.round,10);assert.equal(n.log.length,50);const p=n.players[0];Object.assign(p,{cash:99,reputation:4,commissions:2});n.stalls[0]={ownerId:'a',level:3};const scores=marketScores(n);assert.equal(scores.a,26);const destinations=marketDestinations(n);assert.deepEqual(destinations,[]);});
writeFileSync('qa-workspace/evidence/market-branches.json',JSON.stringify({checks,count:checks.length,fixture:'in-memory isolated engine states; no database mutations'},null,2));console.log(`${checks.length} independent market branch checks passed`);
