import assert from 'node:assert/strict';import {writeFileSync}from'node:fs';import{scorePocketBoard,pocketRequests,pocketOffers,pocketNeighbors,createPocketRun,placePocketTile,replayPocketRun,validatePocketSave}from'../src/lib/pocket-paradise.ts';
const results=[];const mark=(name,details={})=>results.push({name,...details});const score=(tiles,seed='qa-score')=>{const b=Array(20).fill(null);for(const[i,t]of tiles)b[i]=t;return scorePocketBoard(b,seed);};
try{
for(const [name,tiles,key,expected]of [['home park edge',[[0,'home'],[1,'park']],'homes',2],['home park diagonal',[[0,'home'],[6,'park']],'homes',0],['stall path edge',[[0,'stall'],[5,'path']],'stalls',2],['park edge counted once',[[0,'park'],[1,'park']],'parks',1],['path edge counted once',[[0,'path'],[1,'path']],'paths',1],['row wrap not adjacency',[[4,'home'],[5,'park']],'homes',0]]){const r=score(tiles);assert.equal(r[key],expected);assert.equal(r.total,expected);mark(name,{expected,actual:r.total});}
const corner=pocketNeighbors(0);assert.deepEqual(corner.sort((a,b)=>a-b),[1,5]);const interior=pocketNeighbors(6);assert.deepEqual(interior.sort((a,b)=>a-b),[1,5,7,11]);const end=pocketNeighbors(19);assert.deepEqual(end.sort((a,b)=>a-b),[14,18]);mark('corner/interior/end neighbor boundaries');
const seed='qa-bonus',req=pocketRequests(seed)[0];for(const n of [4,5,6]){const board=Array(20).fill(null);for(let i=0;i<n;i++)board[i]=req.tile;const s=scorePocketBoard(board,seed);assert.equal(s.requests[0].complete,n>=5);assert.equal(s.bonuses,n>=5?8:0);mark('nominated request threshold',{n,bonus:s.bonuses});}
const b=Array(20).fill(null);['home','stall','park','path'].forEach((t,j)=>{for(let i=0;i<3;i++)b[j*3+i]=t;});let s=scorePocketBoard(b,seed);assert.equal(s.requests[1].complete,true);assert.equal(s.bonuses,12);b[11]=null;s=scorePocketBoard(b,seed);assert.equal(s.requests[1].complete,false);assert.equal(s.bonuses,0);b[11]='path';b[12]=req.tile;b[13]=req.tile;s=scorePocketBoard(b,seed);assert.equal(s.bonuses,20);mark('all-kind threshold below/at and both bonuses once');
const requests=new Set();for(let i=0;i<200;i++){const seed=`qa-${i}`;requests.add(pocketRequests(seed)[0].tile);for(let t=0;t<20;t++){const offers=pocketOffers(seed,t);assert.equal(offers.length,3);assert.equal(new Set(offers).size,3);assert.ok(offers.every(x=>['home','stall','park','path'].includes(x)));const again=pocketOffers(seed,t);assert.deepEqual(again,offers);}}assert.equal(requests.size,4);mark('200 seeds x20 turns three valid unique deterministic offers; request family variation',{requestFamilies:[...requests]});
let run=createPocketRun('qa-replay','standard');for(let i=0;i<20;i++)run=placePocketTile(run,{cell:i,offer:i%3});const replay=replayPocketRun(run.seed,run.mode,run.moves);assert.deepEqual(replay,run);mark('20-turn varied-offer deterministic replay');
const fail=(name,fn)=>{let thrown=false;try{fn();}catch{thrown=true;}assert.equal(thrown,true);mark(name);};for(const seed of ['',null,'<script>','x'.repeat(101)])fail('invalid seed '+String(seed).slice(0,10),()=>createPocketRun(seed,'standard'));fail('invalid mode',()=>createPocketRun('valid','cheat'));for(const moves of [null,{},Array(21).fill({cell:0,offer:0})])fail('invalid moves array/length',()=>replayPocketRun('valid','standard',moves));for(const move of [null,{}, {cell:-1,offer:0},{cell:20,offer:0},{cell:.5,offer:0},{cell:0,offer:-1},{cell:0,offer:3},{cell:0,offer:.5},{cell:'0',offer:0}])fail('invalid move '+JSON.stringify(move),()=>placePocketTile(createPocketRun('valid','standard'),move));let occupied=placePocketTile(createPocketRun('valid','standard'),{cell:0,offer:0});fail('occupied rejection',()=>placePocketTile(occupied,{cell:0,offer:1}));fail('complete run rejection',()=>placePocketTile(run,{cell:0,offer:0}));for(const value of [null,3,{}, {...run,version:2},{...run,moves:[{cell:-1,offer:0}]}]){const got=validatePocketSave(value);assert.equal(got,null);}const restored=validatePocketSave({...run,board:Array(20).fill('hacked')});assert.deepEqual(restored,run);mark('invalid saves rejected, saved board replay ignores tampering');
}finally{writeFileSync('qa-workspace/evidence/pocket-engine.json',JSON.stringify(results,null,2));}console.log(JSON.stringify({checks:results.length}));
